# Generated by Django 5.1.6 on 2025-03-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_delights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='inventory',
            new_name='quantity',
        ),
    ]
