# Generated by Django 5.1.6 on 2025-03-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_delights', '0002_rename_inventory_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='user',
        ),
        migrations.AddField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
